# Generated by Django 5.0.6 on 2024-06-23 21:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100, verbose_name='Nombre')),
                ('duracion', models.IntegerField(verbose_name='Duración')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_factor', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_fundacion', models.DateField(verbose_name='Fecha de Fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion_genero', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='InformeCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('numero_estudiantes', models.IntegerField(verbose_name='Número de Estudiantes')),
                ('aprobados', models.IntegerField(verbose_name='Aprobados')),
                ('reprobados', models.IntegerField(verbose_name='Reprobados')),
                ('desertores', models.IntegerField(verbose_name='Desertores')),
                ('retirados', models.IntegerField(verbose_name='Retirados')),
            ],
            options={
                'verbose_name': 'Informe de Carrera',
                'verbose_name_plural': 'Informes de Carreras',
            },
        ),
        migrations.CreateModel(
            name='InformeCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('numero_estudiantes', models.IntegerField()),
                ('aprobados', models.IntegerField()),
                ('reprobados', models.IntegerField()),
                ('desertores', models.IntegerField()),
                ('retirados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InformeMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('docente_encargado', models.CharField(max_length=100)),
                ('numero_estudiantes', models.IntegerField()),
                ('aprobados', models.IntegerField()),
                ('reprobados', models.IntegerField()),
                ('desertores', models.IntegerField()),
                ('retirados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_dni', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion_tipo_dni', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_universidad', models.CharField(max_length=100, verbose_name='Nombre universidad')),
                ('direccion_universidad', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono_universidad', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('correo_universidad', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('fecha_fundacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dni', models.CharField(max_length=20, verbose_name='Tipo de DNI')),
                ('numero_dni', models.CharField(max_length=10, verbose_name='Número de DNI')),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(max_length=1, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciclo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.facultad', verbose_name='Facultad'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numero_horas', models.IntegerField(verbose_name='Número de Horas')),
                ('docente_encargado', models.CharField(max_length=100, verbose_name='Docente Encargado')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.ciclo', verbose_name='Ciclo')),
            ],
        ),
        migrations.AddField(
            model_name='facultad',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.universidad', verbose_name='Universidad'),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_secretaria', models.CharField(max_length=100, verbose_name='Código')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre de Rol')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_personal_administrativo', models.CharField(max_length=100, verbose_name='Código')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_docente', models.CharField(max_length=100, verbose_name='Código')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_cuenta', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('contrasenia_cuenta', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('estado_cuenta', models.BooleanField(verbose_name='Estado de Cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('dni', models.CharField(blank=True, max_length=10, null=True, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('rol', models.CharField(choices=[('Personal Administrativo', 'Personal Administrativo'), ('Secretaria', 'Secretaria'), ('Docente', 'Docente')], default='Docente', max_length=50, verbose_name='Rol')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.genero', verbose_name='Género')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tipo_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.tipodni', verbose_name='Tipo de DNI')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
