# Generated by Django 5.0.6 on 2024-06-11 01:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('numero_estudiantes', models.IntegerField(verbose_name='Número de Estudiantes')),
                ('aprobados', models.IntegerField(verbose_name='Aprobados')),
                ('reprobados', models.IntegerField(verbose_name='Reprobados')),
                ('desertores', models.IntegerField(verbose_name='Desertores')),
                ('retirados', models.IntegerField(verbose_name='Retirados')),
            ],
            options={
                'verbose_name': 'Informe de Carrera',
                'verbose_name_plural': 'Informes de Carreras',
            },
        ),
        migrations.CreateModel(
            name='InformeCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('numero_estudiantes', models.IntegerField()),
                ('aprobados', models.IntegerField()),
                ('reprobados', models.IntegerField()),
                ('desertores', models.IntegerField()),
                ('retirados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InformeMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('docente_encargado', models.CharField(max_length=100)),
                ('num_estudiantes', models.IntegerField()),
                ('aprobados', models.IntegerField()),
                ('reprobados', models.IntegerField()),
                ('desertores', models.IntegerField()),
                ('retirados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('NombreUsuario', models.CharField(max_length=50, unique=True)),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=60)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Contrasenia', models.CharField(max_length=50)),
                ('Confirmar_Contrasenia', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
