# Generated by Django 5.0.6 on 2024-07-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='discapacidad',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], verbose_name='Discapacidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='hijos',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], verbose_name='Hijos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='modalidad_estudio',
            field=models.IntegerField(choices=[(0, 'Presencial'), (1, 'Virtual')], verbose_name='Modalidad de Estudio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='origen',
            field=models.IntegerField(choices=[(0, 'No Foráneo'), (1, 'Foráneo')], verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_educacion',
            field=models.IntegerField(choices=[(0, 'Público'), (1, 'Privado')], verbose_name='Tipo de Educación'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='trabajo',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], verbose_name='Trabajo'),
        ),
    ]
