# Generated by Django 5.0.6 on 2024-07-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='numero_ciclo',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
    ]
