# Generated by Django 5.0.6 on 2024-06-15 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100, verbose_name='Nombre')),
                ('duracion', models.IntegerField(verbose_name='Duración')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_fundacion', models.DateField(verbose_name='Fecha de Fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_universidad', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('fecha_fundacion', models.DateField(verbose_name='Fecha de Fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dni', models.CharField(max_length=20, verbose_name='Tipo de DNI')),
                ('numero_dni', models.CharField(max_length=10, verbose_name='Número de DNI')),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(max_length=1, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciclo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.facultad', verbose_name='Facultad'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numero_horas', models.IntegerField(verbose_name='Número de Horas')),
                ('docente_encargado', models.CharField(max_length=100, verbose_name='Docente Encargado')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.ciclo', verbose_name='Ciclo')),
            ],
        ),
        migrations.AddField(
            model_name='facultad',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.universidad', verbose_name='Universidad'),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_secretaria', models.CharField(max_length=100, verbose_name='Código')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, verbose_name='Nombre de Rol')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_personal_administrativo', models.CharField(max_length=100, verbose_name='Código')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_docente', models.CharField(max_length=100, verbose_name='Código')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_cuenta', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('contrasenia_cuenta', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('estado_cuenta', models.BooleanField(verbose_name='Estado de Cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIS.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
