# Generated by Django 5.0.6 on 2024-06-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('Personal Administrativo', 'Personal Administrativo'), ('Secretaria', 'Secretaria'), ('Docente', 'Docente')], default='docente', max_length=50, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_dni',
            field=models.CharField(blank=True, choices=[('Pasaporte', 'Pasaporte'), ('Cedula', 'Cédula')], max_length=20, null=True, verbose_name='Tipo de DNI'),
        ),
    ]
