# Generated by Django 5.0.6 on 2024-07-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='fecha_inicio',
        ),
    ]
