# Generated by Django 5.0.6 on 2024-07-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0002_alter_periodoacademico_estado_periodo_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='unidades',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='estado_periodo_academico',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, verbose_name='Estado'),
        ),
    ]
