# Generated by Django 5.0.6 on 2024-06-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0002_carrera_facultad_informe_universidad_usuario_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_factor', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
    ]
