# Generated by Django 5.0.6 on 2024-07-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0002_rename_datos_historicos_datoshistoricos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodoacademico',
            name='estado_periodo_academico',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10, verbose_name='Estado'),
        ),
    ]
