# Generated by Django 5.0.6 on 2024-07-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIS', '0003_alter_periodoacademico_estado_periodo_academico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaladministrativo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='PersonalAdministrativo',
        ),
        migrations.DeleteModel(
            name='Secretaria',
        ),
    ]
